language: r
cache: packages
dist: trusty
warnings_are_errors: false

addons:
  apt:
    packages:
    - build-essential
    - libxml2-dev
    - autoconf
    - libtool
    - subversion
    - libmagick++-dev

before_install:
- R -e "install.packages(c('devtools','pkgload', 'pkgdown', 'covr'))"
before_script:
- R --no-save <<< 'pkgload::load_all(); devtools::document()'

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email: philipp.muench@helmholtz-hzi.de

