language: r
cache: packages
dist: trusty
warnings_are_errors: false
env:
  global:
  - CODECOV_TOKEN="d64abe59-e0dd-4453-9f36-89c591097d7b"
  - secure: cCt9wBGF2WodOWndDqu8j9t6ZMf730p6gLGuPCoIDefSdxY+02IfbZoNJ+qvGZY0gmEjw6bkZmHl/Q1HPXjHe7dJ0iFvdZtXyGYRiYiKAMYXIR7taultzoXkrGXTQshW5oD6n9UZaJr18GvAmDglDTOdY2BAfCiRbNZv2JYi48MyzoI9SGe+6mUOXhYKu4W6TV2I7ptFRyes8Brd5nsJYmntS8uPo6AyRB2ACEYr9l7JGqZWrTUKv4A439OYGlJRe1RwjOlFSfUUx2DbdZLHc5bJgtSe0y+5EQ8UF0rY/rMFW+0+XMbmMQMJWuNHOaz2UolCVhwKu7yR8l7zWv7yFCvjboVZoEkFomQeMhTq/naNFrKeJ1sq3PAKMTbMiVbSgYb2RM3CU1Bi2HwXVOPSWGACooOJffbo8yjEALR8832jOglKAWlIl671R9jlYYWpAw3TVc34fogr3gA7JWEfjcJNUizifSp+AiY2Q5w4tVXYtbRRJ/+1i9ksFFkSXvvKzrsoPR81TKToqQ6k7cuRZ7BgHWXPAqp6IrdvUfoT0dxbCi4mDskoUHEHxUSH0IupnLU2Q7rKEfcW/SQh5xDMW8B6JQ0mKZGB3Oi0XW1FtvnVPl9YJa5PgJF+qfZEqGiQ8Bu97W05pAGBCg4Vwb1b6Hc4ag+y43h/OT9B2j3E8kA=
addons:
  apt:
    packages:
    - build-essential
    - libxml2-dev
    - autoconf
    - libtool
    - subversion
    - libmagick++-dev
before_install:
  - R -e "install.packages(c('devtools', 'pkgload', 'pkgdown', 'covr'))"
before_script:
  - R --no-save <<< 'pkgload::load_all(); devtools::document()'
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE"
  != "cron" ]] ; then R --no-save <<< "devtools::install(); pkgdown::build_site()";
  git checkout master; export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges
  -n 1)"; git config --global user.name "Travis CI"; git config --global user.email
  "$COMMIT_AUTHOR_EMAIL"; git config credential.helper "store --file=.git/credentials";
  echo "https://${GH_TOKEN}:@github.com" >> .git/credentials; git config push.default
  matching; git add --force man/*; git add --force README.md; git add --force docs/*;
  git rm -r --cached $(find . -type d -name "*_cache"); git commit man DESCRIPTION
  NAMESPACE README.md docs -m "update auto-generated documentation [ci]" -m "$TRAVIS_COMMIT_MSG"
  || true; git push; fi;
  - Rscript -e 'library(covr); covr::codecov()'
notifications:
  slack: bifo-hzi:LHS0Rorop7SBzoQuUVLmnX80
