language: r
cache: packages
dist: trusty
warnings_are_errors: false

env:
  global:
  CODECOV_TOKEN="d64abe59-e0dd-4453-9f36-89c591097d7b"

addons:
  apt:
    packages:
    - build-essential
    - libxml2-dev
    - autoconf
    - libtool
    - subversion
    - libmagick++-dev

before_install:
- R -e "install.packages(c('devtools','pkgload', 'pkgdown', 'covr'))"
before_script:
- R --no-save <<< 'pkgload::load_all(); devtools::document()'

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

notifications:
  email: philipp.muench@helmholtz-hzi.de

